/**
 ** Name: 
 ** Author: 
 ** CreateAt: 
 ** Description: 
**/
/* LIBRARY */
/** LOADING */
export const SET_LOADING = 'SET_LOADING';
/** SETTING */
export const UPDATE_SETTING_WOO = 'UPDATE_SETTING_WOO';
export const UPDATE_SETTING_PAYMENT = 'UPDATE_SETTING_PAYMENT';
export const UPDATE_SETTING_GENERAL = 'UPDATE_SETTING_GENERAL';
export const UPDATE_SETTING_APP = 'UPDATE_SETTING_APP';
export const UPDATE_SETTING_HOME = 'UPDATE_SETTING_HOME';
export const UPDATE_SETTING_SHIPPING_ZONES = 'UPDATE_SETTING_SHIPPING_ZONES';
export const UPDATE_SETTING_COUNTRY = 'UPDATE_SETTING_COUNTRY';
export const UPDATE_ALL_SETTING = 'UPDATE_ALL_SETTING';
export const UPDATE_CHECKOUT_SETTING = 'UPDATE_CHECKOUT_SETTING';
export const REMOVE_ALL_SETTING = 'REMOVE_ALL_SETTING';
/** CONNECTION */
export const UPDATE_CONNECTION_STATUS = 'UPDATE_CONNECTION_STATUS';
/** LANG */
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const SET_DEFAULT = 'SET_DEFAULT';
/** CART */
export const UPDATE_CART = 'UPDATE_CART';
export const ADD_ITEM_CART = 'ADD_ITEM_CART';
export const ADD_ITEM_CART_WEBVIEW = 'ADD_ITEM_CART_WEBVIEW';
export const UPDATE_ITEM_CART = 'UPDATE_ITEM_CART';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';
export const REMOVE_ALL_CART = 'REMOVE_ALL_CART';
export const UPDATE_CART_KEY = 'UPDATE_CART_KEY';
/** USER */
export const UPDATE_USER = 'UPDATE_USER';
export const REMOVE_USER = 'REMOVE_USER';
/** CATEGORY */
export const UPDATE_CATEGORIES_PRODUCT = 'UPDATE_CATEGORIES_PRODUCT';
export const UPDATE_CATEGORIES_NEWS = 'UPDATE_CATEGORIES_NEWS';
export const REMOVE_ALL_CATEGORY = 'REMOVE_ALL_CATEGORY';