require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'appbookit' do
  config = use_native_modules!

  # New pod library
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary.podspec"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'Firebase/Core', '~> 6.3.0'
  pod 'Firebase/AdMob', '~> 6.3.0'
  pod 'Firebase/Messaging', '~> 6.3.0'
  # pod 'Fabric', '~> 1.10.2'
  # pod 'Crashlytics', '~> 3.13.2'
  # End

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  target 'appbookitTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'appbookit-tvOS' do
  # Pods for appbookit-tvOS

  target 'appbookit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
