<?php
  if (! defined('ZS_ACF')) {
    if( function_exists('acf_add_local_field_group') ):

    acf_add_local_field_group(array(
      'key' => 'group_5ea682556a228',
      'title' => 'CategoryMeta Group',
      'fields' => array(
        array(
          'key' => 'field_5ea68267b985e',
          'label' => 'Thumbnail',
          'name' => 'thumbnail',
          'type' => 'image',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'thumbnail',
          'library' => 'all',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'taxonomy',
            'operator' => '==',
            'value' => 'category',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5c231b6aa6f7e',
      'title' => 'PostMeta Group',
      'fields' => array(
        array(
          'key' => 'field_5c2325c463151',
          'label' => 'Gallery',
          'name' => 'gallery',
          'type' => 'gallery',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'medium',
          'insert' => 'append',
          'library' => 'all',
          'min' => '',
          'max' => '',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
        array(
          'key' => 'field_5e9d4e59b5c4d',
          'label' => 'Audio link',
          'name' => 'audio_url',
          'type' => 'url',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
        ),
        array(
          'key' => 'field_5e9d4f24e126f',
          'label' => 'Video link',
          'name' => 'video_url',
          'type' => 'url',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'post',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5e7ae7484b644',
      'title' => 'UserMeta Group',
      'fields' => array(
        array(
          'key' => 'field_5e7ae75d93e6b',
          'label' => 'DOB',
          'name' => 'date_of_birth',
          'type' => 'date_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'display_format' => 'Y-m-d',
          'return_format' => 'Y-m-d',
          'first_day' => 1,
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'current_user',
            'operator' => '==',
            'value' => 'logged_in',
          ),
          array(
            'param' => 'user_form',
            'operator' => '==',
            'value' => 'all',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5bd29cac68dd1',
      'title' => 'ZiniStore App Builder',
      'fields' => array(
        array(
          'key' => 'field_5bd8116b1a75e__trashed',
          'label' => 'Home Page builder',
          'name' => 'zs_mobile_home_builder',
          'type' => 'flexible_content',
          'instructions' => 'Data Builder Block on Mobile Application: Featured news + Post by Category + Videos + Latest Post',
          'required' => 1,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'layouts' => array(
            '5bd8117a64b59' => array(
              'key' => '5bd8117a64b59',
              'name' => 'zs_featured_posts',
              'label' => 'WP Featured Posts',
              'display' => 'row',
              'sub_fields' => array(
                array(
                  'key' => 'field_5bd811b61a760',
                  'label' => 'Featured Posts',
                  'name' => 'zs_featured_posts',
                  'type' => 'relationship',
                  'instructions' => 'Featured posts display on homepage',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => array(
                    0 => 'post',
                  ),
                  'taxonomy' => '',
                  'filters' => array(
                    0 => 'search',
                  ),
                  'elements' => array(
                    0 => 'featured_image',
                  ),
                  'min' => '',
                  'max' => '',
                  'return_format' => 'object',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5c415e128334d' => array(
              'key' => 'layout_5c415e128334d',
              'name' => 'zs_latest_posts',
              'label' => 'WP Latest Posts',
              'display' => 'row',
              'sub_fields' => array(
                array(
                  'key' => 'field_5dd01ce45b25e',
                  'label' => 'Layout style',
                  'name' => 'layout_style',
                  'type' => 'radio',
                  'instructions' => 'Format layout display',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left_thumb' => 'Left Thumb',
                    'right_thumb' => 'Right Thumb',
                    'grid_thumb' => 'Grid Thumb',
                    'card_thumb' => 'Card Thumb',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => '',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5d30472556773',
                  'label' => 'Num.',
                  'name' => 'num_of_post',
                  'type' => 'number',
                  'instructions' => 'Number of latest posts',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => 4,
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'min' => '',
                  'max' => '',
                  'step' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e8d8ed9f2a5c' => array(
              'key' => 'layout_5e8d8ed9f2a5c',
              'name' => 'zs_woo_categories',
              'label' => 'Woo Categories',
              'display' => 'row',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e8d8fe2f2a5f',
                  'label' => 'Thumb Style',
                  'name' => 'thumb_style',
                  'type' => 'radio',
                  'instructions' => 'Format thumbnail style',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'circle' => 'Circle',
                    'square' => 'Square',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => '',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e8d95c036314' => array(
              'key' => 'layout_5e8d95c036314',
              'name' => 'zs_woo_coupons',
              'label' => 'Woo Coupons',
              'display' => 'row',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e8d95d236317',
                  'label' => 'Num.',
                  'name' => 'num_of_coupon',
                  'type' => 'number',
                  'instructions' => 'Number of coupon display on homepage',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => 3,
                  'placeholder' => 'Number of coupon display on homepage',
                  'prepend' => '',
                  'append' => '',
                  'min' => '',
                  'max' => '',
                  'step' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e8d7343a0ff5' => array(
              'key' => 'layout_5e8d7343a0ff5',
              'name' => 'zs_woo_latest_products',
              'label' => 'Woo Newest Products',
              'display' => 'row',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e8d7343a0ff6',
                  'label' => 'Layout style',
                  'name' => 'layout_style',
                  'type' => 'radio',
                  'instructions' => 'Format layout display',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '40',
                    'class' => '',
                    'id' => '',
                  ),
                  'choices' => array(
                    'left_thumb' => 'Left Thumb',
                    'right_thumb' => 'Right Thumb',
                    'grid_thumb' => 'Grid Thumb',
                    'card_thumb' => 'Card Thumb',
                  ),
                  'allow_null' => 0,
                  'other_choice' => 0,
                  'default_value' => '',
                  'layout' => 'horizontal',
                  'return_format' => 'value',
                  'save_other_choice' => 0,
                ),
                array(
                  'key' => 'field_5e8d7343a0ff7',
                  'label' => 'Num.',
                  'name' => 'num_of_latest_product',
                  'type' => 'number',
                  'instructions' => 'Number of newest products',
                  'required' => 0,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                  ),
                  'default_value' => 4,
                  'placeholder' => '',
                  'prepend' => '',
                  'append' => '',
                  'min' => '',
                  'max' => '',
                  'step' => '',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e8ea69c3836d' => array(
              'key' => 'layout_5e8ea69c3836d',
              'name' => 'zs_woo_featured_products',
              'label' => 'Woo Featured Products',
              'display' => 'row',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e8ea69c3836e',
                  'label' => 'Featured Products',
                  'name' => 'zs_featured_products',
                  'type' => 'relationship',
                  'instructions' => 'Featured products display on homepage',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                  ),
                  'post_type' => array(
                    0 => 'product',
                  ),
                  'taxonomy' => '',
                  'filters' => array(
                    0 => 'search',
                  ),
                  'elements' => '',
                  'min' => '',
                  'max' => '',
                  'return_format' => 'object',
                ),
              ),
              'min' => '',
              'max' => '',
            ),
            'layout_5e8d6db34f5cd' => array(
              'key' => 'layout_5e8d6db34f5cd',
              'name' => 'zs_woo_banners',
              'label' => 'Woo Banners',
              'display' => 'row',
              'sub_fields' => array(
                array(
                  'key' => 'field_5e8d6db34f5cf',
                  'label' => 'List banners',
                  'name' => 'list_banners',
                  'type' => 'repeater',
                  'instructions' => 'Upload with format JPG, PNG, GIF. 800x600 px recommendation',
                  'required' => 1,
                  'conditional_logic' => 0,
                  'wrapper' => array(
                    'width' => '30',
                    'class' => '',
                    'id' => '',
                  ),
                  'collapsed' => '',
                  'min' => 0,
                  'max' => 0,
                  'layout' => 'table',
                  'button_label' => '',
                  'sub_fields' => array(
                    array(
                      'key' => 'field_5e8d71334f5d0',
                      'label' => 'Image',
                      'name' => 'image',
                      'type' => 'image',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'return_format' => 'array',
                      'preview_size' => 'thumbnail',
                      'library' => 'all',
                      'min_width' => '',
                      'min_height' => '',
                      'min_size' => '',
                      'max_width' => '',
                      'max_height' => '',
                      'max_size' => '',
                      'mime_types' => '',
                    ),
                    array(
                      'key' => 'field_5e8d71434f5d1',
                      'label' => 'Caption',
                      'name' => 'caption',
                      'type' => 'wysiwyg',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'tabs' => 'all',
                      'toolbar' => 'full',
                      'media_upload' => 1,
                      'delay' => 0,
                    ),
                    array(
                      'key' => 'field_5e8d716a4f5d2',
                      'label' => 'Target URL',
                      'name' => 'url',
                      'type' => 'url',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'default_value' => '',
                      'placeholder' => '',
                    ),
                    array(
                      'key' => 'field_5e8d72074891d',
                      'label' => 'Style',
                      'name' => 'format',
                      'type' => 'select',
                      'instructions' => '',
                      'required' => 0,
                      'conditional_logic' => 0,
                      'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                      ),
                      'choices' => array(
                        'text_above_tl' => 'Top Left',
                        'text_above_tc' => 'Top Center',
                        'text_above_tr' => 'Top Right',
                        'text_above_bl' => 'Bottom Left',
                        'text_above_bc' => 'Bottom Center',
                        'text_above_br' => 'Bottom Right',
                        'text_above_middle' => 'Middle',
                      ),
                      'default_value' => array(
                        0 => 'text_above_middle',
                      ),
                      'allow_null' => 0,
                      'multiple' => 0,
                      'ui' => 0,
                      'return_format' => 'value',
                      'ajax' => 0,
                      'placeholder' => '',
                    ),
                  ),
                ),
              ),
              'min' => '',
              'max' => '',
            ),
          ),
          'button_label' => 'Add Row',
          'min' => '',
          'max' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'options_page',
            'operator' => '==',
            'value' => 'zs_zinistore_builder',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
    ));

    acf_add_local_field_group(array(
      'key' => 'group_5e97d252ae5cb',
      'title' => 'ZiniStore Onboarding Screen',
      'fields' => array(
        array(
          'key' => 'field_5e97d2ff8de65',
          'label' => 'Onboarding Screen?',
          'name' => 'is_show_intro_screen',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => 'Enable onboarding screen which is a virtual unboxing experience that helps users get started with an app.',
          'default_value' => 0,
          'ui' => 0,
          'ui_on_text' => '',
          'ui_off_text' => '',
        ),
        array(
          'key' => 'field_5e97d3b28de66',
          'label' => 'Gallery',
          'name' => 'intro_screen_gallery',
          'type' => 'gallery',
          'instructions' => 'Upload with format JPG, PNG, GIF.',
          'required' => 1,
          'conditional_logic' => array(
            array(
              array(
                'field' => 'field_5e97d2ff8de65',
                'operator' => '==',
                'value' => '1',
              ),
            ),
          ),
          'wrapper' => array(
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'return_format' => 'array',
          'preview_size' => 'bookitshop-intro-screen',
          'insert' => 'append',
          'library' => 'all',
          'min' => '',
          'max' => '',
          'min_width' => '',
          'min_height' => '',
          'min_size' => '',
          'max_width' => '',
          'max_height' => '',
          'max_size' => '',
          'mime_types' => '',
        ),
      ),
      'location' => array(
        array(
          array(
            'param' => 'options_page',
            'operator' => '==',
            'value' => 'zs_zinistore_intro_screen',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'default',
      'label_placement' => 'left',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => true,
      'description' => '',
    ));

    endif;
  }
?>